[project]
name = "soccerway-2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "bs4>=0.0.2",
    "lxml>=5.3.2",
    "requests>=2.32.3",
    "tqdm>=4.67.1",
    "xlwt>=1.3.0",
]
